### ISSUE TITLE
Need help with Torrentio config in addon settings

### ISSUE THREAD

**Issue by onlytanmoy** [Sam-Max/plugin.video.jacktook#4]
Hiya, thanks for this new addon, I am very keen to try this out but not getting how to setup Torrentio :(

In Settings > Torrents > Client = Debrid
Debrid - Authorized my RD
Indexer = Torrentio

Went to https://torrentio.strem.fun/configure
Right clicked on the Install button after setting my config and the string looks like below

stremio://torrentio.strem.fun/sort=qualitysize|<My RD API Key>/manifest.json

What change I need to make to the above URL string before entering into the Torrentio field of the addon?

**Comment by Sam-Max** [comment]
You just need to add the url https://torrentio.strem.fun into the Torrentio field of the addon

**Comment by onlytanmoy** [comment]
Working all fine now, thanks mate 👍

Do you know how can I configure Jacktook as a player in TMDB helper?

Couple of feedback from my end if I may
1. Sort by Quality option under Indexers section of the settings
2. Support for AllDebrid
3. Option to select both Debrid & Torrest under Client in Torrents section of the settings

**Comment by Sam-Max** [comment]
I have not used TMDB helper before, I will try later.

And yes, I will add quality option to Torrentio. For AllDebrid not planning for now to do it. And for suggestion 3 I don't understand what you mean.

**Comment by onlytanmoy** [comment]
Thanks for your response.
Ok, so what I mean is currently in Torrents section you can either select Debrid or Torrest and not both, so if that option is provided then for a particular search I will be able to see all cached results in Debrid and also uncached results via Torrest and then if I want I can either directly stream it or add it to my RD for downloading.

**Comment by Sam-Max** [comment]
Not a bad idea, thanks for suggestion.

**Comment by onlytanmoy** [comment]
Hi mate, currently any movie I scrape via Jacktook keeps appearing in my RD Downloads History (https://real-debrid.com/downloads) literally all of them so like 20 instances of Wonka movie as an example. I want to keep my RD Downloads clutter free as I manually add torrents/hosters to that for downloading & streaming and having all these unwanted downloads makes it difficult to find the one I am looking for, hope you understand. So can something be done about in the addon settings which will prevent the RD Download s from being filled up?

**Comment by Sam-Max** [comment]
> Hi mate, currently any movie I scrape via Jacktook keeps appearing in my RD Downloads History (https://real-debrid.com/downloads) literally all of them so like 20 instances of Wonka movie as an example. I want to keep my RD Downloads clutter free as I manually add torrents/hosters to that for downloading & streaming and having all these unwanted downloads makes it difficult to find the one I am looking for, hope you understand. So can something be done about in the addon settings which will prevent the RD Download s from being filled up?

Sorry for the late response, don't know why I did not see this message before. Regarding your question, I don't know if there is a way to prevent RD from doing this. You have to add magnet to RD cloud in order to get the direct link (checking before if it is already cached). By the way, addon already is compatible with TMDB Helper as a player and added sort by quality a few seconds ago.

**Comment by Sam-Max** [comment]
I found a way to avoid to store torrents on RD Downloads History. I will release an update soon

**Comment by Sam-Max** [comment]
Fixed on 0.1.9

**Comment by onlytanmoy** [comment]
> I found a way to avoid to store torrents on RD Downloads History. I will release an update soon

Brilliant, will look forward to that mate, cheers!

**Comment by onlytanmoy** [comment]
> Fixed on 0.1.9

Just tried with this version and the issue still persists, I could see all 20 search results of 'Poor Things' in my RD Downloads history :(

**Comment by Sam-Max** [comment]
> > Fixed on 0.1.9
> 
> Just tried with this version and the issue still persists, I could see all 20 search results of 'Poor Things' in my RD Downloads history :(

It is working fine for me. Make sure to clean your downloads history first in case it was already there and check the app version if it is correctly updated. I tested now with that title and no downloads history

**Comment by onlytanmoy** [comment]
Don't know why I am still having the issue. Confirmed JT version is 0.1.9.
Cleared all my RD Downloads history, removed everything, screenshot below
![image](https://github.com/Sam-Max/plugin.video.jacktook/assets/48493659/01365c29-8553-4599-97d2-c3b5e63cf547)
Searched for the movie via JT and can now see my RD Downloads as below
![image](https://github.com/Sam-Max/plugin.video.jacktook/assets/48493659/4f6da489-c011-4fc5-b36d-462d849b0e5d)
Is there any other settings in the addon I need to check?

**Comment by Sam-Max** [comment]
I tested now again, and no download history. In the code the magnet is deleted after getting link, so should not happen. Write me here https://t.me/sammax09 if you can to help you better

**Comment by onlytanmoy** [comment]
Thanks for the discussion earlier on TG mate where I was able to explain you the issue better :)

**Comment by onlytanmoy** [comment]
Confirmed, tested, this is now solved, no more Download History, thank you.

Keeping this open for below :)

> Thanks for your response. Ok, so what I mean is currently in Torrents section you can either select Debrid or Torrest and not both, so if that option is provided then for a particular search I will be able to see all cached results in Debrid and also uncached results via Torrest and then if I want I can either directly stream it or add it to my RD for downloading.

**Comment by onlytanmoy** [comment]
The add-on now provides option to select all in settings i.e., Debrid, Torrest & Elementum.
Closing this ticket, thanks mate.
