### ISSUE TITLE
Addon Won't Launch - Python Error?

### ISSUE THREAD

**Issue by jollyhiggler** [Sam-Max/plugin.video.jacktook#64]
Windows 11
Kodi 21.0
Jacktook 0.3.4

"Jacktook Error. Check the log for more information" 

```
2024-11-24 17:07:16.309 T:4492    error <general>: EXCEPTION: Unknown addon id 'plugin.video.jacktorr'.
2024-11-24 17:07:16.313 T:4492    error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'TypeError'>
                                                   Error Contents: unsupported operand type(s) for |: 'type' and 'type'
                                                   Traceback (most recent call last):
                                                     File "C:\Users\xx\AppData\Roaming\Kodi\addons\plugin.video.jacktook\jacktook.py", line 3, in <module>
                                                       from lib.navigation import run
                                                     File "C:\Users\xx\AppData\Roaming\Kodi\addons\plugin.video.jacktook\lib\navigation.py", line 8, in <module>
                                                       from lib.api.debrid.premiumize_api import Premiumize
                                                     File "C:\Users\xx\AppData\Roaming\Kodi\addons\plugin.video.jacktook\lib\api\debrid\premiumize_api.py", line 16, in <module>
                                                       class Premiumize(DebridClient):
                                                     File "C:\Users\xx\AppData\Roaming\Kodi\addons\plugin.video.jacktook\lib\api\debrid\premiumize_api.py", line 42, in Premiumize
                                                       ) -> dict | list:
                                                   TypeError: unsupported operand type(s) for |: 'type' and 'type'
                                                   -->End of Python script error report<--
                                                   
2024-11-24 17:07:16.617 T:9288    error <general>: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.jacktook/
2024-11-24 17:07:16.630 T:13900   error <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.jacktook/) failed
```

**Comment by Sam-Max** [comment]
It should be working now

**Comment by jollyhiggler** [comment]
Unfortunately still unable to launch Version 0.3.5

Different error this time though:

```
2024-11-25 11:29:24.787 T:6864    error <general>: EXCEPTION: Unknown addon id 'plugin.video.jacktorr'.
2024-11-25 11:29:24.791 T:6864    error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'SyntaxError'>
                                                   Error Contents: invalid syntax (real_debrid_api.py, line 33)
                                                   Traceback (most recent call last):
                                                     File "C:\Users\naylo\AppData\Roaming\Kodi\addons\plugin.video.jacktook\jacktook.py", line 3, in <module>
                                                       from lib.navigation import run
                                                     File "C:\Users\naylo\AppData\Roaming\Kodi\addons\plugin.video.jacktook\lib\navigation.py", line 9, in <module>
                                                       from lib.api.debrid.real_debrid_api import RealDebrid
                                                     File "C:\Users\naylo\AppData\Roaming\Kodi\addons\plugin.video.jacktook\lib\api\debrid\real_debrid_api.py", line 33
                                                       match error_code:
                                                             ^
                                                   SyntaxError: invalid syntax
                                                   -->End of Python script error report<--
                                                   
2024-11-25 11:29:25.027 T:1712    error <general>: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.jacktook/
2024-11-25 11:29:25.042 T:17328   error <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.jacktook/) failed
```

**Comment by jollyhiggler** [comment]
Unfortunately still unable to launch on Version 0.3.5

Different error reported this time though:

```
2024-11-25 11:29:24.787 T:6864    error <general>: EXCEPTION: Unknown addon id 'plugin.video.jacktorr'.
2024-11-25 11:29:24.791 T:6864    error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'SyntaxError'>
                                                   Error Contents: invalid syntax (real_debrid_api.py, line 33)
                                                   Traceback (most recent call last):
                                                     File "C:\Users\xx\AppData\Roaming\Kodi\addons\plugin.video.jacktook\jacktook.py", line 3, in <module>
                                                       from lib.navigation import run
                                                     File "C:\Users\xx\AppData\Roaming\Kodi\addons\plugin.video.jacktook\lib\navigation.py", line 9, in <module>
                                                       from lib.api.debrid.real_debrid_api import RealDebrid
                                                     File "C:\Users\xx\AppData\Roaming\Kodi\addons\plugin.video.jacktook\lib\api\debrid\real_debrid_api.py", line 33
                                                       match error_code:
                                                             ^
                                                   SyntaxError: invalid syntax
                                                   -->End of Python script error report<--
                                                   
2024-11-25 11:29:25.027 T:1712    error <general>: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.jacktook/
2024-11-25 11:29:25.042 T:17328   error <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.jacktook/) failed
```

**Comment by Sam-Max** [comment]
Update your python version on Windows to 3.10 or newer.

**Comment by jollyhiggler** [comment]
I didn't previously have python installed on this Windows machine. I've just put 3.13.0 on it but it made no difference.

This does seem to be specific to the Windows environment though: No issue launching Jacktook 0.3.5 on an Android device.

**Comment by latinokodi** [comment]
Same issue here. Working fine on Android, but in Windows:

`2024-11-25 09:48:38.561 T:21636    info <general>: CAddonMgr::ADDON::CAddonMgr::FindAddon: script.otaku.mappings v24.05.02 installed
2024-11-25 09:48:38.816 T:21636    info <general>: CAddonMgr::ADDON::CAddonMgr::FindAddon: plugin.video.jacktook v0.3.5 installed
2024-11-25 09:48:39.026 T:20020   error <general>: EXCEPTION: Unknown addon id 'plugin.video.jacktorr'.
2024-11-25 09:48:39.278 T:15900    info <general>: Skipped 1 duplicate messages..
2024-11-25 09:48:39.278 T:15900   error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'SyntaxError'>
                                                   Error Contents: invalid syntax (real_debrid_api.py, line 33)
                                                   Traceback (most recent call last):
                                                     File "D:\Latino Kodi 100\Latino Kodi 100 Wizard\LKOmega21.1Tests\portable_data\addons\plugin.video.jacktook\jacktook.py", line 3, in <module>
                                                       from lib.navigation import run
                                                     File "D:\Latino Kodi 100\Latino Kodi 100 Wizard\LKOmega21.1Tests\portable_data\addons\plugin.video.jacktook\lib\navigation.py", line 9, in <module>
                                                       from lib.api.debrid.real_debrid_api import RealDebrid
                                                     File "D:\Latino Kodi 100\Latino Kodi 100 Wizard\LKOmega21.1Tests\portable_data\addons\plugin.video.jacktook\lib\api\debrid\real_debrid_api.py", line 33
                                                       match error_code:
                                                             ^
                                                   SyntaxError: invalid syntax
                                                   -->End of Python script error report<--
                                                   
2024-11-25 09:48:39.378 T:21636   error <general>: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.jacktook/
2024-11-25 09:48:39.385 T:9440    error <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.jacktook/) failed
2024-11-25 09:48:41.957 T:20020    info <general>: [###JACKTOOKLOG###] Checking Kodi version
2024-11-25 09:48:44.569 T:1268     info <general>: [###JACKTOOKLOG###] Update Check Service Started
2024-11-25 09:49:30.141 T:1268     info <general>: [###JACKTOOKLOG###] 0.3.5`

**Comment by Sam-Max** [comment]
I will change the code on the addon to make it compatible with python version integrated on Kodi for windows

**Comment by Sam-Max** [comment]
@latinokodi @jollyhiggler download the project as zip file and test now, should be working fine, as I change code not compatible with python interpreter that Kodi uses on Windows.

**Comment by latinokodi** [comment]
Working perfectly on Windows now!. Thanks!!
![Screenshot_3](https://github.com/user-attachments/assets/733e1372-ff6b-4927-8ba4-8ad39c433828)

**Comment by jollyhiggler** [comment]
Thanks
